config/routes.rb
Fizzbuzz::Application.routes.draw do
  resources :fizzies

end

app/models/fizzy.rb
class Fizzy < ActiveRecord::Base
  
  # Stores Fizz Buzz in an array and returns it.
  def self.fizz
    result = Array.new
    
    # main loop for fizzbuzz
    for i in 1..100 do
      if i % 15 == 0
        result[i] = 'fizzbuzz'
      elsif i % 5 == 0
        result[i] = 'buzz'
      elsif i % 3 == 0
        result[i] = 'fizz'
      else
        result[i] = i.to_s
      end
    end
    
    # return the result of fizzbuzz
    result
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fizzies_controller.rb
class FizziesController < ApplicationController
  # GET /fizzies
  # GET /fizzies.xml
  def index
    @fizzies = Fizzy.all
    @fizz = Fizzy.fizz

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fizzies }
    end
  end

  # GET /fizzies/1
  # GET /fizzies/1.xml
  def show
    @fizzy = Fizzy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fizzy }
    end
  end

  # GET /fizzies/new
  # GET /fizzies/new.xml
  def new
    @fizzy = Fizzy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fizzy }
    end
  end

  # GET /fizzies/1/edit
  def edit
    @fizzy = Fizzy.find(params[:id])
  end

  # POST /fizzies
  # POST /fizzies.xml
  def create
    @fizzy = Fizzy.new(params[:fizzy])

    respond_to do |format|
      if @fizzy.save
        format.html { redirect_to(@fizzy, :notice => 'Fizzy was successfully created.') }
        format.xml  { render :xml => @fizzy, :status => :created, :location => @fizzy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fizzy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fizzies/1
  # PUT /fizzies/1.xml
  def update
    @fizzy = Fizzy.find(params[:id])

    respond_to do |format|
      if @fizzy.update_attributes(params[:fizzy])
        format.html { redirect_to(@fizzy, :notice => 'Fizzy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fizzy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fizzies/1
  # DELETE /fizzies/1.xml
  def destroy
    @fizzy = Fizzy.find(params[:id])
    @fizzy.destroy

    respond_to do |format|
      format.html { redirect_to(fizzies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fizzies_helper.rb
module FizziesHelper
end

app/views/fizzies/_form.html.erb
<%= form_for(@fizzy) do |f| %>
  <% if @fizzy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fizzy.errors.count, "error") %> prohibited this fizzy from being saved:</h2>

      <ul>
      <% @fizzy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fizzies/edit.html.erb
<h1>Editing fizzy</h1>

<%= render 'form' %>

<%= link_to 'Show', @fizzy %> |
<%= link_to 'Back', fizzies_path %>

app/views/fizzies/index.html.erb
<h1>Fizzbuzz</h1>

<p>
Write a program that prints the numbers from 1 to 100. But for multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz". 
</p>

<h1>Result</h1>
<% @fizz.each do |row| %>
    <%= row %><br/>
<% end %>

app/views/fizzies/new.html.erb
<h1>New fizzy</h1>

<%= render 'form' %>

<%= link_to 'Back', fizzies_path %>

app/views/fizzies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_fizzy_path(@fizzy) %> |
<%= link_to 'Back', fizzies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fizzbuzz</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>